# Generated by Django 5.2.4 on 2026-08-12 04:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0017_backfill_missing_student_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.CharField(max_length=40)),
                ('instrument_version', models.CharField(default='1', max_length=20)),
                ('answers', models.JSONField(default=dict)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='admissions.studentprofile')),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
                'indexes': [models.Index(fields=['student', 'challenge', '-completed_at'], name='admissions__student_d8fb52_idx')],
            },
        ),
    ]
